import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {auth0} from "@/lib/auth/auth";
Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();
  const user = session?.user;
  const isAuthenticated = !!user;

  return (
    <html lang="en">
      <body className={"flex flex-col h-screen"}>
        <div className={"flex items-center justify-between px-8 py-4"}>
          {isAuthenticated ? (
            <>
              Hello, {user.name}
              <a href="/auth/logout">Logout</a>
            </>
          ) : (
            <a href="/auth/login">Login</a>
          )}
        </div>

        <div className={"flex-grow flex flex-col"}>
          {children}
        </div>
      </body>
    </html>
  );
}
