import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "@/lib/main-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Placeholder for Lucide Icons if not directly available in this environment.
// In a real Next.js app, you'd install and import from 'lucide-react'.
const HomeIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>
    <polyline points="9 22 9 12 15 12 15 22"/>
  </svg>
);
const SettingsIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.78 1.22a2 2 0 0 0 .73 2.73l.15.08a2 2 0 0 1 1 1.73v.44a2 2 0 0 0 2 2v.18a2 2 0 0 1 1 1.73l.43.25a2 2 0 0 1 2 0l.15-.08a2 2 0 0 0 2.73.73l.78 1.22a2 2 0 0 0-.73 2.73l-.15.08a2 2 0 0 1-1 1.73v.44a2 2 0 0 0 2 2v.18a2 2 0 0 1 1 1.73l.43.25a2 2 0 0 1 2 0l.15-.08a2 2 0 0 0 2.73-.73l.78-1.22a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.73v-.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.78-1.22a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.73v-.44a2 2 0 0 0-2-2v-.18a2 2 0 0 1-1-1.73l-.43-.25a2 2 0 0 1-2 0l-.15.08a2 2 0 0 0-2.73-.73L12.22 2z"/>
    <circle cx="12" cy="12" r="3"/>
  </svg>
);
const UserIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/>
    <circle cx="12" cy="7" r="4"/>
  </svg>
);
const InfoIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-info"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></svg>
);

// Navigation item type definition
interface NavItem {
  name: string;
  icon: React.ElementType; // Use React.ElementType for component type
  path: string;
}

// Define the navigation items
const navItems: NavItem[] = [
  { name: 'Home', icon: HomeIcon, path: '/' },
  { name: 'Settings', icon: SettingsIcon, path: '/settings' },
  { name: 'Profile', icon: UserIcon, path: '/profile' },
  { name: 'About', icon: InfoIcon, path: '/about' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/*// The main container. On small screens (default), it's a column with nav at bottom (flex-col-reverse).*/}
        {/*// On medium screens and up, it becomes a row with nav on the left (md:flex-row).*/}
        {/*// min-h-screen ensures it takes full viewport height.*/}
        <div className="flex flex-col-reverse md:flex-row min-h-screen bg-gray-50 text-gray-800 font-sans">
          <MainNav/>

          {/* Main content area */}
          <main className="
          flex-1
          p-4 md:p-8
          pb-16 md:pb-4 /* Add bottom padding on mobile for the navigation bar */
          overflow-auto
          flex flex-col
          items-center md:items-start
          justify-center
          min-h-[calc(100vh-64px)] md:min-h-screen
        ">
            <div className="max-w-4xl w-full bg-white p-6 md:p-10 shadow-lg rounded-lg border border-gray-200">
              <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6 text-center md:text-left">
                Welcome to your new Web App!
              </h1>
              <p className="text-lg text-gray-700 leading-relaxed mb-4 text-center md:text-left">
                This is the main content area. The navigation bar on the
                <span className="md:hidden"> bottom </span>
                <span className="hidden md:inline"> left </span>
                allows you to switch between different sections of your application.
                Currently showing content for: <span className="font-semibold text-blue-600"></span>.
              </p>
              <p className="text-md text-gray-600 mb-4 text-center md:text-left">
                You can populate this area with dashboards, forms, lists, or any other dynamic content specific to each page.
              </p>
              <div className="mt-8 text-center md:text-left">
                <button className="
                bg-blue-500 hover:bg-blue-700
                text-white font-bold py-3 px-6
                rounded-lg shadow-md hover:shadow-lg
                transition-all duration-300 transform hover:-translate-y-1
                focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50
              ">
                  Get Started
                </button>
              </div>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
