import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/main-nav";
import {Toaster, ToasterProps} from "sonner";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div className="flex flex-col min-h-screen">
        {/* Desktop Navigation - fixed at the top */}
        <div className="hidden md:block fixed top-0 left-0 right-0 z-40 border-b">
          <MainNav />
        </div>

        {/* Mobile Navigation - fixed at the bottom */}
        <div className="md:hidden fixed bottom-0 left-0 right-0 z-40 border-t">
          <MainNav />
        </div>

        {/* Main content area */}
        <main className="
            flex-grow
            flex flex-col
            md:px-8
            pt-0 md:pt-[var(--nav-height)]
            pb-[var(--nav-height-mobile)] md:pb-0
          ">
          {children}
        </main>
      </div>
      <Toaster
        position="top-right"
        richColors
        closeButton
        expand={true}
        toastOptions={{
          // Default duration for all toasts
          duration: 3000,
          // Custom styling
        }}
        style={{
          zIndex: 9999,
        }}
      />
    </body>
    </html>
  );
}
