// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type Category = {
  id: bigint,
  name: string,
  normalisedName: string,
  colorHex: string,
  sortOrder: number,
  userId: Identity,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Category {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU64Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("normalisedName", AlgebraicType.createStringType()),
      new ProductTypeElement("colorHex", AlgebraicType.createStringType()),
      new ProductTypeElement("sortOrder", AlgebraicType.createI32Type()),
      new ProductTypeElement("userId", AlgebraicType.createIdentityType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Category): void {
    Category.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Category {
    return Category.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


