// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type Entry = {
  id: bigint,
  startTime: Timestamp,
  endTime: Timestamp | undefined,
  recordedTime: Timestamp,
  duration: TimeDuration,
  previousEntryId: bigint | undefined,
  nextEntryId: bigint | undefined,
  userId: Identity,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Entry {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU64Type()),
      new ProductTypeElement("startTime", AlgebraicType.createTimestampType()),
      new ProductTypeElement("endTime", AlgebraicType.createOptionType(AlgebraicType.createTimestampType())),
      new ProductTypeElement("recordedTime", AlgebraicType.createTimestampType()),
      new ProductTypeElement("duration", AlgebraicType.createTimeDurationType()),
      new ProductTypeElement("previousEntryId", AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
      new ProductTypeElement("nextEntryId", AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
      new ProductTypeElement("userId", AlgebraicType.createIdentityType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Entry): void {
    Entry.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Entry {
    return Entry.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


